# Generated by Django 3.2.15 on 2022-09-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ML_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('modelFile', models.FileField(upload_to='Classifier/MLModels')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
