# Generated by Django 3.2.15 on 2022-09-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_model',
            name='priority',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
