# Generated by Django 3.2.15 on 2022-09-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0002_ml_model_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
