# Generated by Django 3.2.15 on 2022-09-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0003_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='petsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
