# Generated by Django 3.2.14 on 2022-09-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0004_auto_20220914_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsmodel',
            name='field',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
