# Generated by Django 3.2.14 on 2022-09-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0005_alter_petsmodel_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsmodel',
            name='caption',
            field=models.CharField(default='pet', max_length=200),
        ),
        migrations.AlterField(
            model_name='petsmodel',
            name='field',
            field=models.ImageField(upload_to='images'),
        ),
    ]
