# Generated by Django 3.2.14 on 2022-09-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0006_auto_20220915_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsmodel',
            old_name='field',
            new_name='image',
        ),
    ]
